# Generated by Django 5.0.2 on 2024-03-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0002_product_categories_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderuser",
            name="products",
            field=models.ManyToManyField(
                through="orders.OrderProducts", to="products.product"
            ),
        ),
    ]
