# Generated by Django 5.0.2 on 2024-03-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproducts",
            old_name="products",
            new_name="product",
        ),
    ]
