# Generated by Django 5.0.2 on 2024-02-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderuser",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="orderuser",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderuser",
            name="table_id",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="menu.table"
            ),
        ),
        migrations.AddField(
            model_name="orderuser",
            name="user_id",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="menu.user"
            ),
        ),
        migrations.AlterField(
            model_name="orderuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
