# Generated by Django 5.0.2 on 2024-03-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_products_orderproducts_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproducts",
            old_name="order_user",
            new_name="order_user_id",
        ),
    ]
