# Generated by Django 5.0.2 on 2024-03-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderuser_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
