# Generated by Django 5.0.2 on 2024-02-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderuser_created_at_orderuser_is_paid_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderuser",
            name="products",
            field=models.ManyToManyField(
                through="orders.ProductOrderUser", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="productorderuser",
            name="product_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
