# Generated by Django 5.0.2 on 2024-02-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderuser_products_productorderuser_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
