# Generated by Django 5.0.2 on 2024-02-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_orderuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
