# Generated by Django 5.0.2 on 2024-02-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
