# Generated by Django 5.0.2 on 2024-02-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_table_name_alter_user_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="table",
            new_name="table_id",
        ),
    ]
