# Generated by Django 5.0.2 on 2024-02-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_rename_table_user_table_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="table_id",
            new_name="table",
        ),
    ]
