# Generated by Django 5.0.2 on 2024-03-05 20:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_username_alter_review_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
