# Generated by Django 5.0.2 on 2024-02-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_orderuser_id"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="orders",
            field=models.ManyToManyField(to="orders.orderuser"),
        ),
    ]
